safe: true
lsi: false
pygments: true
markdown: kramdown
gems: [jekyll-scholar]
exclude: ["template.markdown", "newpost.rb"]
paginate: 2

authors:
  michael:
    display_name: Michael Landis
    name: Michael Landis
    email: mlandis@gmail.com
    twitter: landismj
    github: mlandis

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "%{reference}"

  replace_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
